[profile.default]
src = "src"
test = "poc-tests"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
verbosity = 2
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/"
]
via_ir = true
auto_detect_solc = true

[profile.rocketpool]
src = "test"
solc = "0.7.6"
optimizer = true
optimizer_runs = 200
evm_version = "istanbul"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/demo"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/demo"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
